version: "3"
services:

  mongodb:
    image: mongo:5.0.5
    container_name: mongodb
    ports:
      - 27018:27017
    command: [ "--replSet", "rs0", "--bind_ip_all" ]
    volumes:
      - ./0-mongo-init.js:/docker-entrypoint-initdb.d/0-mongo-init.js:ro
      - ./data:/data/db

  appsmith:
    image: appsmith/appsmith-ce:latest
    depends_on:
      - mongodb
    container_name: appsmith
    environment:
      APPSMITH_MONGODB_URI: mongodb+srv://mongodb/appsmith
    ports:
      - "8031:80"
      - "444:443"
      - "9001:9001"
    volumes:
      - ./stacks:/appsmith-stacks
